[platformio]
default_envs = unified

[env]
lib_extra_dirs =
	lib/interfaces
	lib/config
	lib/buses
	lib/protocols
	lib/links
	lib/buffering
platform = espressif32
framework = arduino
monitor_speed = 115200

[env:unified]
board = esp32-c3-devkitm-1
board_build.flash_mode = dio
build_flags =
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
	sandeepmistry/LoRa @ ^0.8.0
	knolleary/PubSubClient @ ^2.8
	bblanchon/ArduinoJson @ ^7
build_src_filter = -<*> +<main.cpp> +<nodes/>

[env:lilygo_lora]
board = ttgo-lora32-v21
lib_deps =
	sandeepmistry/LoRa @ ^0.8.0
	knolleary/PubSubClient @ ^2.8
	bblanchon/ArduinoJson @ ^7
build_src_filter = -<*> +<main.cpp> +<nodes/>
