[platformio]
default_envs = end_node

[env]
lib_extra_dirs =
	lib/interfaces
	lib/config
	lib/buses
	lib/protocols
	lib/links
	lib/buffering

[esp32]
platform = espressif32
framework = arduino
monitor_speed = 115200
test_filter = test_board_*

[env:end_node]
extends = esp32
board = esp32-c3-devkitm-1
board_build.flash_mode = dio
build_flags =
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
	bblanchon/ArduinoJson @ ^7
build_src_filter = -<*> +<end_node_main.cpp> +<nodes/rs485_node.cpp> +<nodes/ir_node.cpp> +<nodes/cv_node.cpp>

[env:lilygo_lora]
extends = esp32
board = ttgo-lora32-v21
lib_deps =
	sandeepmistry/LoRa @ ^0.8.0
	knolleary/PubSubClient @ ^2.8
	bblanchon/ArduinoJson @ ^7
build_src_filter = -<*> +<lora_main.cpp> +<nodes/substation.cpp> +<nodes/gateway.cpp>

[env:test_c3]
extends = env:end_node
build_flags =
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=0
test_filter = test_qemu_*
test_testing_command =
	python3
	tools/qemu_test.py
	${platformio.build_dir}/${this.__env__}
	${platformio.packages_dir}